const ACFG=window.APP_CONFIG||{};let adminPin='',products=[],report=null,editingId='',pendingImageData='';
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)],money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
function apiUrl(){return String(ACFG.ORDER_WEBAPP_URL||'').trim()}
function requireApi(){if(!apiUrl()){q('#loginMsg').textContent='Antes de usar o painel, publique o Google Apps Script e coloque a URL /exec em ORDER_WEBAPP_URL no config.js.';return false}return true}
async function apiGet(action,params={}){const u=new URL(apiUrl());u.searchParams.set('action',action);Object.entries(params).forEach(([k,v])=>{if(v!==''&&v!=null)u.searchParams.set(k,v)});u.searchParams.set('_t',Date.now());const r=await fetch(u,{cache:'no-store'});return r.json()}
async function apiPost(payload){const body=new URLSearchParams();body.set('payload',JSON.stringify(payload));const r=await fetch(apiUrl(),{method:'POST',body});return r.json()}
async function login(){if(!requireApi())return;adminPin=q('#pin').value.trim();if(!adminPin){q('#loginMsg').textContent='Digite o PIN.';return}q('#loginMsg').textContent='Verificando...';try{const d=await apiGet('report',{pin:adminPin});if(!d.ok)throw new Error(d.error||'Acesso negado');q('#loginCard').hidden=true;q('#panel').hidden=false;report=d;await loadProducts();renderReport(d)}catch(e){q('#loginMsg').textContent='Não foi possível entrar: '+e.message}}
async function loadProducts(){const d=await apiGet('products');if(!d.ok)throw new Error(d.error||'Erro ao carregar produtos');products=d.products||[];renderProducts()}
function effectivePromo(p){if(!p.promocao||!Number(p.preco_promocional))return false;const now=new Date(),a=p.promo_inicio?new Date(p.promo_inicio):null,b=p.promo_fim?new Date(p.promo_fim):null;return(!a||now>=a)&&(!b||now<=b)}
function renderProducts(){const term=(q('#productSearch')?.value||'').toLowerCase();const list=products.filter(p=>!term||(`${p.nome} ${p.categoria}`).toLowerCase().includes(term));q('#productsTable').innerHTML=`<table><thead><tr><th>Imagem</th><th>Produto</th><th>Categoria</th><th>Preço</th><th>Promoção</th><th>Status</th><th>Atualização</th><th>Ações</th></tr></thead><tbody>${list.map(p=>`<tr data-id="${p.id}"><td>${p.imagem?`<img class="product-thumb" src="${p.imagem}" alt="">`:'—'}</td><td><strong>${esc(p.nome)}</strong><br><small>${esc(p.descricao||'')}</small></td><td>${esc(p.categoria)}</td><td>${effectivePromo(p)?`<del>${money(p.preco)}</del><br><strong>${money(p.preco_promocional)}</strong>`:`<strong>${money(p.preco)}</strong>`}</td><td>${p.promocao?`<span class="promo-pill">🔥 ${money(p.preco_promocional)}</span>`:'—'}</td><td><span class="status-pill ${p.ativo?'status-on':'status-off'}">${p.ativo?'● DISPONÍVEL':'● INDISPONÍVEL'}</span></td><td><small>${fmtDate(p.atualizado_em)}</small></td><td><div class="row-actions"><button class="edit-row" data-edit="${p.id}">Editar</button><button class="save-row" data-toggle="${p.id}">${p.ativo?'Pausar':'Ativar'}</button></div></td></tr>`).join('')}</tbody></table>`;qa('[data-edit]').forEach(b=>b.onclick=()=>openProduct(products.find(p=>p.id===b.dataset.edit)));qa('[data-toggle]').forEach(b=>b.onclick=()=>toggleProduct(b.dataset.toggle))}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmtDate(v){if(!v)return'—';const d=new Date(v);return isNaN(d)?String(v):d.toLocaleString('pt-BR')}
function isoDate(v){if(!v)return'';const d=new Date(v);return isNaN(d)?'':d.toISOString().slice(0,10)}
function openProduct(p=null){editingId=p?.id||'';pendingImageData='';q('#modalTitle').textContent=p?'Editar produto':'Novo produto';q('#pName').value=p?.nome||'';q('#pCategory').value=p?.categoria||'Bovino';q('#pPrice').value=p?.preco||'';q('#pUnit').value=p?.unidade||'kg';q('#pDescription').value=p?.descricao||'';q('#pActive').checked=p?!!p.ativo:true;q('#pPromo').checked=!!p?.promocao;q('#pPromoPrice').value=p?.preco_promocional||'';q('#pPromoStart').value=isoDate(p?.promo_inicio);q('#pPromoEnd').value=isoDate(p?.promo_fim);q('#pImageUrl').value=p?.imagem||'';q('#pPreview').src=p?.imagem||'';q('#productMsg').textContent='';q('#productModal').hidden=false}
function closeModal(){q('#productModal').hidden=true;editingId='';pendingImageData=''}
async function toggleProduct(id){const p=products.find(x=>x.id===id);if(!p)return;await saveProductObject({...p,ativo:!p.ativo});await loadProducts()}
async function saveProductObject(product){return apiPost({action:editingId?'updateProduct':'createProduct',pin:adminPin,product})}
async function uploadPendingImage(name){if(!pendingImageData)return q('#pImageUrl').value.trim();q('#productMsg').textContent='Enviando imagem...';const d=await apiPost({action:'uploadImage',pin:adminPin,nome:name,data:pendingImageData});if(!d.ok)throw new Error(d.error||'Falha ao enviar imagem');return d.url}
async function saveProduct(){const name=q('#pName').value.trim();if(!name){q('#productMsg').textContent='Informe o nome do produto.';return}q('#saveProductBtn').disabled=true;q('#productMsg').textContent='Salvando...';try{const image=await uploadPendingImage(name);const product={id:editingId||slug(name)+'-'+Date.now(),nome:name,categoria:q('#pCategory').value,preco:Number(q('#pPrice').value||0),unidade:q('#pUnit').value,ativo:q('#pActive').checked,descricao:q('#pDescription').value.trim(),imagem:image,promocao:q('#pPromo').checked,preco_promocional:Number(q('#pPromoPrice').value||0),promo_inicio:q('#pPromoStart').value,promo_fim:q('#pPromoEnd').value};const d=await apiPost({action:editingId?'updateProduct':'createProduct',pin:adminPin,product});if(!d.ok)throw new Error(d.error||'Erro ao salvar');q('#productMsg').textContent='Salvo. O app do cliente receberá a alteração na próxima sincronização.';await loadProducts();setTimeout(closeModal,700)}catch(e){q('#productMsg').textContent='Erro: '+e.message}finally{q('#saveProductBtn').disabled=false}}
function slug(s){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}
async function compressImage(file){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const max=1100,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);resolve(c.toDataURL('image/jpeg',.76))};img.onerror=reject;img.src=url})}
async function useFile(e){const f=e.target.files?.[0];if(!f)return;pendingImageData=await compressImage(f);q('#pPreview').src=pendingImageData;q('#pImageUrl').value=''}
function useUrl(){pendingImageData='';q('#pPreview').src=q('#pImageUrl').value.trim()}
async function publishSeeds(){if(!confirm('Enviar o catálogo inicial para a planilha PRODUTOS? Produtos com o mesmo ID serão atualizados.'))return;const seeds=(window.SEED_PRODUCTS||[]).map(p=>({...p,promocao:false,preco_promocional:0}));const d=await apiPost({action:'bulkProducts',pin:adminPin,products:seeds});if(!d.ok)return alert(d.error||'Erro');await loadProducts();alert(`${d.count} produtos enviados.`)}
async function loadReport(){const params={pin:adminPin,from:q('#fromDate').value,to:q('#toDate').value};const d=await apiGet('report',params);if(!d.ok)throw new Error(d.error||'Erro');report=d;renderReport(d)}
function renderReport(d){const k=d.kpis||{};q('#kpis').innerHTML=[['Pedidos',k.pedidos||0],['Faturamento',money(k.faturamento)],['Ticket médio',money(k.ticket_medio)],['Entregas',k.entregas||0],['Retiradas',k.retiradas||0]].map(x=>`<div class="kpi"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('');q('#topProducts').innerHTML=(d.top_produtos||[]).map((x,i)=>`<div class="ranking-row"><span>${i+1}. ${esc(x.nome)}<br><small>${Number(x.quantidade).toLocaleString('pt-BR')} ${Number(x.quantidade)>10?'g/itens':'unid.'}</small></span><strong>${money(x.faturamento)}</strong></div>`).join('')||'Sem vendas no período.';q('#neighborhoods').innerHTML=(d.bairros||[]).map(x=>`<div class="ranking-row"><span>${esc(x.bairro)}</span><strong>${money(x.faturamento)}</strong></div>`).join('')||'Sem entregas no período.';renderOrders(d.pedidos||[])}
function renderOrders(rows){q('#ordersTable').innerHTML=`<table><thead><tr><th>Pedido</th><th>Data</th><th>Cliente</th><th>Entrega</th><th>Total</th><th>Status</th></tr></thead><tbody>${rows.map(o=>`<tr><td><strong>${esc(o.id)}</strong></td><td>${fmtDate(o.data)}</td><td>${esc(o.cliente)}<br><small>${esc(o.telefone)}</small></td><td>${o.recebimento==='entrega'?`${esc(o.bairro)}<br>${esc(o.endereco)}${o.localizacao?`<br><a class="order-route" href="${o.localizacao}" target="_blank">📍 Abrir rota</a>`:''}`:'Retirada na loja'}</td><td><strong>${money(o.total)}</strong></td><td><select data-status-id="${o.id}">${['NOVO','EM SEPARAÇÃO','PRONTO','SAIU PARA ENTREGA','CONCLUÍDO','CANCELADO'].map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select></td></tr>`).join('')}</tbody></table>`;qa('[data-status-id]').forEach(s=>s.onchange=async()=>{const d=await apiPost({action:'updateOrderStatus',pin:adminPin,id:s.dataset.statusId,status:s.value});if(!d.ok)alert(d.error||'Erro ao atualizar status')})}
q('#enterBtn').onclick=login;q('#pin').onkeydown=e=>{if(e.key==='Enter')login()};q('#syncBtn').onclick=async()=>{await Promise.all([loadProducts(),loadReport()])};q('#publishSeedsBtn').onclick=publishSeeds;q('#newProductBtn').onclick=()=>openProduct();q('#productSearch').oninput=renderProducts;q('#reportBtn').onclick=loadReport;q('#saveProductBtn').onclick=saveProduct;q('#pImageFile').onchange=useFile;q('#useUrlBtn').onclick=useUrl;qa('[data-close-modal]').forEach(x=>x.onclick=closeModal);qa('[data-tab]').forEach(b=>b.onclick=()=>{qa('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));qa('.tab-panel').forEach(x=>x.classList.toggle('active',x.id==='tab-'+b.dataset.tab));if(b.dataset.tab!=='prices')loadReport().catch(()=>{})});
