const cfg = window.APP_CONFIG || {};
const money = v => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
const CART_KEY='opeitica:carrinho-v1';
const CUSTOMER_KEY='opeitica:cliente-v1';
const state={products:[],cart:[],category:'Todos',query:'',location:null,fulfillment:'retirada'};
const DELIVERY_AREAS=[['Montese',15],['Parangaba',10],['Maraponga',10],['Pici',10],['Bela Vista',8],['Demócrito Rocha',8],['Henrique Jorge',8],['Vila Pery',6],['Manoel Sátiro',6],['Jatobá',6],['Pq. São José',6],['Pq. Santa Rosa',6],['Canindezinho',6],['Mondubim',7],['Conjunto Esperança',7],['Conjunto Ceará',5],['João XXIII',6],['Granja Lisboa',4],['Bom Sucesso',6],['Granja Portugal',4],['Bom Jardim',4],['Siqueira',6],['Benfica',20],['Centro',20],['Auta Nunes',12],['Quintino Cunha',15],['Barra do Ceará',25],['Genibaú',10],['Passaré',15]];
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
function escapeHTML(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function setSync(status,label,detail=''){const d=$('#syncDot'),l=$('#syncLabel'),t=$('#syncTime');if(d)d.className='dot'+(status?` ${status}`:'');if(l)l.textContent=label;if(t)t.textContent=detail;}
function parseCSV(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++;continue}if(c==='"'){quoted=!quoted;continue}if(c===','&&!quoted){row.push(cell);cell='';continue}if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell='';continue}cell+=c}row.push(cell);if(row.some(x=>x.trim()))rows.push(row);if(!rows.length)return[];const h=rows.shift().map(x=>x.trim().toLowerCase());return rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,(r[i]??'').trim()])))}
function qualifyName(name,category){const n=String(name||'').trim(),c=String(category||'').toLowerCase();if(c.includes('suí')||c.includes('sui')){if(!/su[ií]n/i.test(n))return `${n} Suíno`}if(c.includes('bov')){if(!/bovin/i.test(n))return `${n} Bovino`}return n;}
function normalizeProduct(p,i){const raw=String(p.preco??p.price??0).replace(/\s/g,'').replace('R$','').replace(/\.(?=\d{3}(\D|$))/g,'').replace(',','.');const categoria=p.categoria||p.category||'Outros';return{id:p.id||`produto-${i}`,categoria,nome:qualifyName(p.nome||p.name||`Produto ${i+1}`,categoria),preco:Number(raw)||0,unidade:(p.unidade||p.unit||'kg').toLowerCase(),ativo:!['não','nao','false','0','inativo'].includes(String(p.ativo??'sim').toLowerCase()),descricao:p.descricao||p.description||'',imagem:p.imagem||p.image||''};}
function normalizeSeeds(){return(window.SEED_PRODUCTS||[]).filter(p=>p.ativo!==false).map((p,i)=>normalizeProduct(p,i));}
function persistCart(){try{localStorage.setItem(CART_KEY,JSON.stringify(state.cart));}catch(e){}}
function restoreCart(){try{const x=JSON.parse(localStorage.getItem(CART_KEY)||'[]');if(Array.isArray(x))state.cart=x.map(i=>({...i,total:Number(i.total)||0,preco:Number(i.preco)||0}));}catch(e){state.cart=[]}}
function persistCustomer(){try{localStorage.setItem(CUSTOMER_KEY,JSON.stringify({name:$('#customerName')?.value||'',phone:$('#customerPhone')?.value||'',address:$('#customerAddress')?.value||'',reference:$('#customerReference')?.value||'',area:$('#deliveryArea')?.value||'',fulfillment:state.fulfillment}));}catch(e){}}
function restoreCustomer(){try{const c=JSON.parse(localStorage.getItem(CUSTOMER_KEY)||'{}');if($('#customerName'))$('#customerName').value=c.name||'';if($('#customerPhone'))$('#customerPhone').value=c.phone||'';if($('#customerAddress'))$('#customerAddress').value=c.address||'';if($('#customerReference'))$('#customerReference').value=c.reference||'';if($('#deliveryArea')&&c.area)$('#deliveryArea').value=c.area;setFulfillment(c.fulfillment||'retirada');}catch(e){setFulfillment('retirada')}}
function useCachedImmediately(){try{const cached=JSON.parse(localStorage.getItem('opeitica:lastProducts')||'null');if(Array.isArray(cached)&&cached.length){state.products=cached.map((p,i)=>normalizeProduct(p,i));buildTabs();renderProducts();setSync('ok','Catálogo pronto','Verificando preços atuais em segundo plano');return true}}catch(e){}state.products=normalizeSeeds();buildTabs();renderProducts();setSync('','Catálogo disponível','Usando catálogo inicial');return false;}
async function fetchFreshProducts(){if(!cfg.SHEET_CSV_URL)throw new Error('sheet-not-configured');const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),Number(cfg.DATA_TIMEOUT_MS)||5000);try{const sep=cfg.SHEET_CSV_URL.includes('?')?'&':'?';const res=await fetch(`${cfg.SHEET_CSV_URL}${sep}_t=${Date.now()}`,{cache:'no-store',signal:ctrl.signal,headers:{'Cache-Control':'no-cache, no-store, max-age=0','Pragma':'no-cache'}});if(!res.ok)throw new Error(`HTTP ${res.status}`);const data=parseCSV(await res.text()).map(normalizeProduct).filter(p=>p.ativo);if(!data.length)throw new Error('empty');localStorage.setItem('opeitica:lastProducts',JSON.stringify(data));localStorage.setItem('opeitica:lastSync',new Date().toISOString());return data}finally{clearTimeout(timer)}}
function syncCartPrices(){let changed=false;state.cart.forEach(item=>{const p=state.products.find(x=>x.id===item.id);if(p){item.nome=p.nome;item.categoria=p.categoria;if(Number(item.preco)!==Number(p.preco)){item.preco=p.preco;recalcItem(item);changed=true}}});if(changed){persistCart();updateCart()}}
async function refreshProducts(manual=false){if(!cfg.SHEET_CSV_URL){setSync('','Catálogo disponível','Planilha de preços ainda não conectada');return}setSync('',manual?'Atualizando preços...':'Verificando preços...','Seu orçamento continua disponível');try{state.products=await fetchFreshProducts();syncCartPrices();buildTabs();renderProducts();setSync('ok','Preços atualizados',`Agora • ${new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`)}catch(e){setSync('error','Catálogo disponível','Não foi possível conferir a planilha agora')}}
function buildTabs(){const tabs=$('#categoryTabs');if(!tabs)return;const cats=['Todos',...new Set(state.products.map(p=>p.categoria))];if(!cats.includes(state.category))state.category='Todos';tabs.innerHTML='';cats.forEach(cat=>{const b=document.createElement('button');b.type='button';b.textContent=cat;b.className=cat===state.category?'active':'';b.onclick=()=>{state.category=cat;buildTabs();renderProducts()};tabs.appendChild(b)})}
function addItem(p,grams,note=''){const qty=p.unidade==='kit'?1:grams/1000;const existing=state.cart.find(x=>x.id===p.id&&(x.note||'')===note);if(existing){if(p.unidade==='kit')existing.qty+=1;else existing.grams+=grams;recalcItem(existing)}else state.cart.push({key:`${p.id}-${Date.now()}-${Math.random()}`,id:p.id,nome:p.nome,categoria:p.categoria,preco:p.preco,unidade:p.unidade,qty,grams:p.unidade==='kit'?null:grams,note,total:p.unidade==='kit'?p.preco:p.preco*qty});persistCart();updateCart();openCart()}
function renderProducts(){const grid=$('#productGrid');if(!grid)return;const term=state.query.trim().toLowerCase();const items=state.products.filter(p=>(state.category==='Todos'||p.categoria===state.category)&&(!term||`${p.nome} ${p.categoria} ${p.descricao||''}`.toLowerCase().includes(term)));grid.innerHTML='';if(!items.length){grid.innerHTML='<p class="empty">Nenhum produto encontrado.</p>';return}items.forEach(p=>{const tpl=$('#productTemplate');if(!tpl)return;const node=tpl.content.cloneNode(true);let grams=1000;$('h3',node).textContent=p.nome;$('.category-badge',node).textContent=p.categoria;$('.description',node).textContent=p.descricao||'';$('.price',node).textContent=money(p.preco);$('.unit-label',node).textContent=p.unidade==='kit'?'/ kit':'/ kg';const img=$('.product-image',node),ph=$('.product-placeholder',node);if(p.imagem&&img){img.src=p.imagem;img.alt=p.nome;img.onload=()=>{img.classList.add('show');if(ph)ph.style.display='none'};img.onerror=()=>img.removeAttribute('src')}const controls=$('.weight-controls',node),live=$('.live-calc',node),add=$('.add-btn',node),note=$('.note',node);const updateLive=()=>{if(!live)return;if(p.unidade==='kit')live.innerHTML=`1 kit = <strong>${money(p.preco)}</strong>`;else live.innerHTML=`${grams>=1000?(grams/1000).toLocaleString('pt-BR')+' kg':grams+' g'} = <strong>${money(p.preco*(grams/1000))}</strong>`};if(p.unidade==='kit'){if(controls)controls.style.display='none'}else if(controls){$$('[data-weight]',controls).forEach(btn=>btn.onclick=()=>{grams=Number(btn.dataset.weight)||1000;$$('[data-weight]',controls).forEach(x=>x.classList.toggle('active',x===btn));const custom=$('.custom-weight',controls);if(custom)custom.value='';updateLive()});const custom=$('.custom-weight',controls);if(custom)custom.oninput=()=>{const v=Number(custom.value);if(v>0){grams=v;$$('[data-weight]',controls).forEach(x=>x.classList.remove('active'));updateLive()}}}updateLive();if(add)add.onclick=()=>addItem(p,grams,note?note.value.trim():'');grid.appendChild(node)})}
function recalcItem(item){if(item.unidade==='kit'){item.qty=Math.max(1,Math.round(Number(item.qty)||1));item.total=item.preco*item.qty}else{item.grams=Math.max(1,Number(item.grams)||1);item.qty=item.grams/1000;item.total=item.preco*item.qty}}
function cartSubtotal(){return state.cart.reduce((s,i)=>s+(Number(i.total)||0),0)}
function selectedDelivery(){const o=$('#deliveryArea')?.selectedOptions?.[0];return o?{name:o.value,fee:Number(o.dataset.fee||0)}:{name:'',fee:0}}
function updateFloatingCart(){const count=$('#cartCount'),total=$('.cart-fab-total'),summary=$('#cartFabSummary');if(count)count.textContent=String(state.cart.length);if(total)total.textContent=money(cartSubtotal());if(summary)summary.textContent=state.cart.length?`${state.cart.length} ${state.cart.length===1?'produto':'produtos'} selecionados`:'Seu orçamento está vazio'}
function updateCart(){updateFloatingCart();const wrap=$('#cartItems');if(!wrap)return;wrap.innerHTML='';if(!state.cart.length)wrap.innerHTML='<div class="empty">Sua cesta está vazia. Escolha os produtos; todos ficarão reunidos aqui.</div>';state.cart.forEach(item=>{const el=document.createElement('div');el.className='cart-item';const value=item.unidade==='kit'?item.qty:item.grams,suffix=item.unidade==='kit'?'kit':'g';el.innerHTML=`<div class="cart-item-main"><strong>${escapeHTML(item.nome)}</strong><small>${escapeHTML(item.categoria||'')} • ${money(item.preco)} ${item.unidade==='kit'?'/ kit':'/ kg'}</small><div class="cart-qty-control"><button type="button" class="qty-minus">−</button><input class="cart-qty-input" type="number" min="1" value="${value}" inputmode="numeric"><span>${suffix}</span><button type="button" class="qty-plus">+</button></div><strong class="cart-item-total">${money(item.total)}</strong>${item.note?`<small>Obs.: ${escapeHTML(item.note)}</small>`:''}</div><button type="button" class="remove-item">Remover</button>`;const input=$('.cart-qty-input',el),apply=v=>{const n=Math.max(1,Number(v)||1);if(item.unidade==='kit')item.qty=Math.round(n);else item.grams=n;recalcItem(item);input.value=item.unidade==='kit'?item.qty:item.grams;$('.cart-item-total',el).textContent=money(item.total);persistCart();updateFloatingCart();updateTotals()};input.oninput=()=>{if(input.value)apply(input.value)};$('.qty-minus',el).onclick=()=>apply(Number(input.value)-(item.unidade==='kit'?1:50));$('.qty-plus',el).onclick=()=>apply(Number(input.value)+(item.unidade==='kit'?1:50));$('.remove-item',el).onclick=()=>{state.cart=state.cart.filter(x=>x.key!==item.key);persistCart();updateCart()};wrap.appendChild(el)});updateTotals()}
function setFulfillment(type){state.fulfillment=type==='entrega'?'entrega':'retirada';$$('[data-fulfillment-choice]').forEach(b=>b.classList.toggle('active',b.dataset.fulfillmentChoice===state.fulfillment));const radio=$(`input[name="fulfillment"][value="${state.fulfillment}"]`);if(radio)radio.checked=true;updateTotals();persistCustomer()}
function fulfillment(){return state.fulfillment}
function updateTotals(){const subtotal=cartSubtotal(),delivery=fulfillment()==='entrega'?selectedDelivery().fee:0;if($('#subtotal'))$('#subtotal').textContent=money(subtotal);if($('#deliveryFee'))$('#deliveryFee').textContent=money(delivery);if($('#grandTotal'))$('#grandTotal').textContent=money(subtotal+delivery);if($('#deliveryRow'))$('#deliveryRow').classList.toggle('is-hidden',fulfillment()!=='entrega');if($('#deliveryFields'))$('#deliveryFields').classList.toggle('is-hidden',fulfillment()!=='entrega');$$('[data-preview-fulfillment]').forEach(b=>b.classList.toggle('active',b.dataset.previewFulfillment===fulfillment()))}
function openCart(){const s=$('#cartSheet');if(s){s.classList.add('open');s.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}}
function closeCart(){const s=$('#cartSheet');if(s){s.classList.remove('open');s.setAttribute('aria-hidden','true');document.body.style.overflow=''}}
function customerData(){return{name:$('#customerName')?.value.trim()||'',phone:$('#customerPhone')?.value.trim()||'',address:$('#customerAddress')?.value.trim()||'',reference:$('#customerReference')?.value.trim()||'',area:selectedDelivery(),type:fulfillment()}}
function validateOrder(){if(!state.cart.length){alert('Adicione produtos à cesta.');return false}const c=customerData();if(!c.name||!c.phone){alert('Informe o nome e o WhatsApp do cliente. Esses dados são preenchidos apenas uma vez para todo o orçamento.');return false}if(c.type==='entrega'&&(!c.area.name||!c.address)){alert('Selecione o bairro e informe o endereço da entrega.');return false}return true}
function mapsClientLink(){return state.location?`https://www.google.com/maps?q=${state.location.lat},${state.location.lng}`:''}
function buildOrderText(orderId=''){const c=customerData(),delivery=c.type==='entrega'?c.area.fee:0;const lines=[`*ORÇAMENTO - ${cfg.BUSINESS_NAME||'Atacadão da Carne O Peitica'}*`];if(orderId)lines.push(`Código: ${orderId}`);lines.push(`Cliente: ${c.name}`,`Telefone: ${c.phone}`,'');state.cart.forEach((i,n)=>{lines.push(`${n+1}. *${i.nome}*`,`Categoria: ${i.categoria||'-'}`,`Quantidade: ${i.unidade==='kit'?`${i.qty} kit(s)`:`${i.grams} g`}`,`Subtotal: ${money(i.total)}`);if(i.note)lines.push(`Observação: ${i.note}`);lines.push('')});lines.push(`Produtos: ${money(cartSubtotal())}`,`Recebimento: ${c.type==='entrega'?'ENTREGA':'RETIRADA NA LOJA'}`);if(c.type==='entrega'){lines.push(`Bairro: ${c.area.name}`,`Taxa: ${money(delivery)}`,`Endereço: ${c.address}`);if(c.reference)lines.push(`Referência: ${c.reference}`);if(mapsClientLink())lines.push(`Localização: ${mapsClientLink()}`)}lines.push(`*TOTAL: ${money(cartSubtotal()+delivery)}*`);return lines.join('\n')}
function makePdfBlob(orderId=''){if(!window.jspdf?.jsPDF)return null;const{jsPDF}=window.jspdf,doc=new jsPDF({unit:'mm',format:'a4'}),c=customerData(),delivery=c.type==='entrega'?c.area.fee:0;doc.setFillColor(159,16,16);doc.rect(0,0,210,32,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(18);doc.text('ATACADÃO DA CARNE O PEITICA',14,14);doc.setFontSize(9);doc.setFont('helvetica','normal');doc.text(orderId?`Orçamento ${orderId}`:'Orçamento / Pedido',14,22);doc.text(new Date().toLocaleString('pt-BR'),196,22,{align:'right'});doc.setTextColor(25,22,20);let y=42;doc.setFont('helvetica','bold');doc.setFontSize(12);doc.text('Dados do cliente',14,y);y+=7;doc.setFont('helvetica','normal');doc.setFontSize(10);doc.text(`Nome: ${c.name}`,14,y);y+=6;doc.text(`Telefone: ${c.phone}`,14,y);y+=6;doc.text(`Recebimento: ${c.type==='entrega'?'Entrega':'Retirada na loja'}`,14,y);y+=6;if(c.type==='entrega'){doc.text(`Bairro: ${c.area.name} | Taxa: ${money(delivery)}`,14,y);y+=6;doc.text(`Endereço: ${c.address}`,14,y,{maxWidth:180});y+=8;if(c.reference){doc.text(`Referência: ${c.reference}`,14,y,{maxWidth:180});y+=7}if(mapsClientLink()){doc.setTextColor(159,16,16);doc.textWithLink('Abrir localização do cliente no mapa',14,y,{url:mapsClientLink()});doc.setTextColor(25,22,20);y+=8}}doc.setDrawColor(220);doc.line(14,y,196,y);y+=8;doc.setFont('helvetica','bold');doc.text('Itens do orçamento',14,y);y+=7;doc.setFont('helvetica','normal');state.cart.forEach((i,n)=>{if(y>260){doc.addPage();y=20}doc.setFont('helvetica','bold');doc.text(`${n+1}. ${i.nome}`,14,y,{maxWidth:100});doc.setFont('helvetica','normal');doc.text(i.unidade==='kit'?`${i.qty} kit(s)`:`${i.grams} g`,132,y);doc.text(money(i.total),196,y,{align:'right'});y+=5;doc.setTextColor(95);doc.text(`Categoria: ${i.categoria||'-'} | Preço: ${money(i.preco)} ${i.unidade==='kit'?'/ kit':'/ kg'}`,18,y,{maxWidth:170});y+=5;if(i.note){doc.text(`Observação: ${i.note}`,18,y,{maxWidth:170});y+=6}doc.setTextColor(25)});y+=3;if(y>270){doc.addPage();y=20}doc.line(14,y,196,y);y+=8;doc.text(`Produtos: ${money(cartSubtotal())}`,196,y,{align:'right'});y+=6;if(c.type==='entrega'){doc.text(`Entrega: ${money(delivery)}`,196,y,{align:'right'});y+=6}doc.setFont('helvetica','bold');doc.setFontSize(14);doc.setTextColor(159,16,16);doc.text(`TOTAL: ${money(cartSubtotal()+delivery)}`,196,y,{align:'right'});y+=12;doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor(90);doc.text(cfg.ADDRESS||'Rua Edison Martins, 530 - Fortaleza/CE',14,y);doc.text(`WhatsApp: ${cfg.WHATSAPP||'5585989626829'}`,14,y+5);return doc.output('blob')}
function downloadPdf(){if(!validateOrder())return;const blob=makePdfBlob();if(!blob){alert('Não foi possível gerar o PDF neste navegador.');return}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`orcamento-opeitica-${Date.now()}.pdf`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
async function sendWhatsApp(){if(!validateOrder())return;const direct=`https://wa.me/${cfg.WHATSAPP||'5585989626829'}?text=${encodeURIComponent(buildOrderText())}`;window.open(direct,'_blank','noopener')}
function setupDeliveryAreas(){const sel=$('#deliveryArea');if(!sel)return;DELIVERY_AREAS.slice().sort((a,b)=>a[0].localeCompare(b[0],'pt-BR')).forEach(([name,fee])=>{const o=document.createElement('option');o.value=name;o.dataset.fee=String(fee);o.textContent=`${name} — ${money(fee)}`;sel.appendChild(o)});sel.onchange=()=>{updateTotals();persistCustomer()}}
function requestLocation(){if(!navigator.geolocation){$('#locationStatus').textContent='Localização indisponível neste navegador.';return}const btn=$('#locationBtn');btn.disabled=true;btn.textContent='📍 Obtendo localização...';navigator.geolocation.getCurrentPosition(pos=>{state.location={lat:pos.coords.latitude,lng:pos.coords.longitude};$('#locationStatus').innerHTML=`✅ Localização adicionada. <a href="${mapsClientLink()}" target="_blank" rel="noopener">Abrir mapa</a>`;btn.textContent='✅ Localização adicionada';btn.disabled=false},()=>{$('#locationStatus').textContent='Não foi possível obter a localização. Libere a permissão do navegador.';btn.textContent='📍 Tentar novamente';btn.disabled=false},{enableHighAccuracy:true,timeout:10000,maximumAge:30000})}
function init(){setupDeliveryAreas();restoreCart();useCachedImmediately();updateCart();restoreCustomer();refreshProducts(false);$('#refreshBtn')?.addEventListener('click',()=>refreshProducts(true));$('#searchInput')?.addEventListener('input',e=>{state.query=e.target.value;renderProducts()});$('#cartFab')?.addEventListener('click',openCart);$$('[data-close-cart]').forEach(x=>x.onclick=closeCart);$$('[data-preview-fulfillment]').forEach(b=>b.onclick=()=>{setFulfillment(b.dataset.previewFulfillment);openCart()});$$('[data-fulfillment-choice]').forEach(b=>b.onclick=()=>setFulfillment(b.dataset.fulfillmentChoice));$$('input[name="fulfillment"]').forEach(r=>r.onchange=()=>setFulfillment(r.value));['customerName','customerPhone','customerAddress','customerReference'].forEach(id=>$('#'+id)?.addEventListener('input',persistCustomer));$('#locationBtn')?.addEventListener('click',requestLocation);$('#sendBtn')?.addEventListener('click',sendWhatsApp);$('#pdfBtn')?.addEventListener('click',downloadPdf);if($('#mapsLink'))$('#mapsLink').href=cfg.MAPS_URL||'#';if($('#whatsappTop'))$('#whatsappTop').href=cfg.WHATSAPP_BUSINESS_URL||`https://wa.me/${cfg.WHATSAPP||'5585989626829'}`;if(cfg.INSTAGRAM_URL&&$('#instagramLink')){$('#instagramLink').href=cfg.INSTAGRAM_URL;$('#instagramLink').classList.remove('is-disabled')}if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=8'))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
