window.SEED_PRODUCTS = [
  {id:'suino-bisteca',categoria:'Suíno',nome:'Bisteca Suína',preco:19,unidade:'kg',ativo:true,imagem:'https://images.pexels.com/photos/7333262/pexels-photo-7333262.jpeg?auto=compress&cs=tinysrgb&w=900'},
  {id:'suino-bife',categoria:'Suíno',nome:'Bife Suíno',preco:21,unidade:'kg',ativo:true,imagem:'https://images.pexels.com/photos/10647859/pexels-photo-10647859.jpeg?auto=compress&cs=tinysrgb&w=900'},
  {id:'suino-pernil',categoria:'Suíno',nome:'Pernil Suíno',preco:17,unidade:'kg',ativo:true,imagem:'https://images.pexels.com/photos/7333262/pexels-photo-7333262.jpeg?auto=compress&cs=tinysrgb&w=900'},
  {id:'suino-palheta',categoria:'Suíno',nome:'Palheta Suína',preco:17,unidade:'kg',ativo:true,imagem:'https://images.pexels.com/photos/10647859/pexels-photo-10647859.jpeg?auto=compress&cs=tinysrgb&w=900'},
  {id:'suino-barriga',categoria:'Suíno',nome:'Barriga Suína',preco:20,unidade:'kg',ativo:true,imagem:'https://images.pexels.com/photos/10647859/pexels-photo-10647859.jpeg?auto=compress&cs=tinysrgb&w=900'},
  {id:'suino-costela',categoria:'Suíno',nome:'Costela Suína',preco:23,unidade:'kg',ativo:true,imagem:'https://images.pexels.com/photos/7333262/pexels-photo-7333262.jpeg?auto=compress&cs=tinysrgb&w=900'},
  {id:'sarrabulho',categoria:'Suíno',nome:'Sarrabulho Suíno',preco:7,unidade:'kg',ativo:true},
  {id:'kit-feijoada',categoria:'Suíno',nome:'Kit Feijoada Suíno',preco:10,unidade:'kg',ativo:true},
  {id:'toucinho',categoria:'Suíno',nome:'Toucinho Suíno',preco:12,unidade:'kg',ativo:true,imagem:'https://images.pexels.com/photos/10647859/pexels-photo-10647859.jpeg?auto=compress&cs=tinysrgb&w=900'},
  {id:'tripa',categoria:'Suíno',nome:'Tripa Suína',preco:25,unidade:'kg',ativo:true},

  {id:'bovino-bisteca',categoria:'Bovino',nome:'Bisteca Bovina',preco:32,unidade:'kg',ativo:true,imagem:'https://images.pexels.com/photos/11677646/pexels-photo-11677646.jpeg?auto=compress&cs=tinysrgb&w=900'},
  {id:'bovino-bife',categoria:'Bovino',nome:'Bife Bovino',preco:39,unidade:'kg',ativo:true,imagem:'https://images.pexels.com/photos/1314041/pexels-photo-1314041.jpeg?auto=compress&cs=tinysrgb&w=900'},
  {id:'carne-moida',categoria:'Bovino',nome:'Carne Moída Bovina',preco:34,unidade:'kg',ativo:true,imagem:'https://images.pexels.com/photos/4661802/pexels-photo-4661802.jpeg?auto=compress&cs=tinysrgb&w=900'},
  {id:'carne-moida-especial',categoria:'Bovino',nome:'Carne Moída Especial Bovina',preco:20,unidade:'kg',ativo:true,imagem:'https://images.pexels.com/photos/4661802/pexels-photo-4661802.jpeg?auto=compress&cs=tinysrgb&w=900'},
  {id:'picadinho',categoria:'Bovino',nome:'Picadinho Bovino',preco:34,unidade:'kg',ativo:true,imagem:'https://images.pexels.com/photos/15508166/pexels-photo-15508166.jpeg?auto=compress&cs=tinysrgb&w=900'},
  {id:'lombo',categoria:'Bovino',nome:'Lombo Bovino',preco:28,unidade:'kg',ativo:true,imagem:'https://images.pexels.com/photos/1314041/pexels-photo-1314041.jpeg?auto=compress&cs=tinysrgb&w=900'},
  {id:'strogonoff',categoria:'Bovino',nome:'Strogonoff Bovino',preco:39,unidade:'kg',ativo:true,imagem:'https://images.pexels.com/photos/4661802/pexels-photo-4661802.jpeg?auto=compress&cs=tinysrgb&w=900'},
  {id:'costela-peito',categoria:'Bovino',nome:'Costela / Peito Bovino',preco:27,unidade:'kg',ativo:true,imagem:'https://images.pexels.com/photos/15508166/pexels-photo-15508166.jpeg?auto=compress&cs=tinysrgb&w=900'},
  {id:'figado',categoria:'Bovino',nome:'Fígado Bovino',preco:18,unidade:'kg',ativo:true},
  {id:'coxao-mole',categoria:'Bovino',nome:'Coxão Mole Bovino',preco:45,unidade:'kg',ativo:true,imagem:'https://images.pexels.com/photos/1314041/pexels-photo-1314041.jpeg?auto=compress&cs=tinysrgb&w=900'},
  {id:'coxao-duro',categoria:'Bovino',nome:'Coxão Duro Bovino',preco:40,unidade:'kg',ativo:true,imagem:'https://images.pexels.com/photos/1314041/pexels-photo-1314041.jpeg?auto=compress&cs=tinysrgb&w=900'},
  {id:'lagarto',categoria:'Bovino',nome:'Lagarto Bovino',preco:40,unidade:'kg',ativo:true,imagem:'https://images.pexels.com/photos/4661802/pexels-photo-4661802.jpeg?auto=compress&cs=tinysrgb&w=900'},
  {id:'patinho',categoria:'Bovino',nome:'Patinho Bovino',preco:45,unidade:'kg',ativo:true,imagem:'https://images.pexels.com/photos/1314041/pexels-photo-1314041.jpeg?auto=compress&cs=tinysrgb&w=900'},
  {id:'osso-buco',categoria:'Bovino',nome:'Osso Buco Bovino',preco:28,unidade:'kg',ativo:true,imagem:'https://images.pexels.com/photos/11677646/pexels-photo-11677646.jpeg?auto=compress&cs=tinysrgb&w=900'},
  {id:'panelada',categoria:'Bovino',nome:'Panelada Bovina',preco:18,unidade:'kg',ativo:true},
  {id:'coracao',categoria:'Bovino',nome:'Coração Bovino (peça inteira)',preco:19,unidade:'kg',ativo:true},
  {id:'rabada',categoria:'Bovino',nome:'Rabada Bovina (peça inteira)',preco:28,unidade:'kg',ativo:true},
  {id:'mao-de-vaca',categoria:'Bovino',nome:'Mão de Vaca Bovina (peça inteira)',preco:19,unidade:'kg',ativo:true},

  {id:'kit-familia',categoria:'Kits',nome:'Kit Família',preco:130,unidade:'kit',ativo:true,descricao:'1kg Picadinho + 1kg Carne Moída + 1kg Cozido Bovino + 1kg Pernil Suíno + 1kg Bisteca Suína',imagem:'https://images.pexels.com/photos/15508166/pexels-photo-15508166.jpeg?auto=compress&cs=tinysrgb&w=900'},
  {id:'kit-premium',categoria:'Kits',nome:'Kit Premium',preco:90,unidade:'kit',ativo:true,descricao:'500g Strogonoff + 500g Bife do Patinho + 500g Bisteca Bovina + 500g Carne do Sol + 500g Bife Suíno',imagem:'https://images.pexels.com/photos/1314041/pexels-photo-1314041.jpeg?auto=compress&cs=tinysrgb&w=900'},
  {id:'kit-protein-70',categoria:'Kits',nome:'Kit Protein 70',preco:70,unidade:'kit',ativo:true,descricao:'500g Carne Moída + 500g Picadinho + 500g Bisteca Suína + 500g Pernil + 500g Bife',imagem:'https://images.pexels.com/photos/15508166/pexels-photo-15508166.jpeg?auto=compress&cs=tinysrgb&w=900'},
  {id:'kit-protein-50',categoria:'Kits',nome:'Kit Protein 50',preco:50,unidade:'kit',ativo:true,descricao:'500g Carne Moída + 500g Picadinho + 500g Bisteca Suína + 500g Pernil',imagem:'https://images.pexels.com/photos/15508166/pexels-photo-15508166.jpeg?auto=compress&cs=tinysrgb&w=900'},
  {id:'kit-pettica',categoria:'Kits',nome:'Kit Pettica',preco:90,unidade:'kit',ativo:true,descricao:'500g Carne do Sol + 500g Fraldinha + 500g Contrafilé + 500g Picanha Suína + 500g Linguiça Premium',imagem:'https://images.pexels.com/photos/15508166/pexels-photo-15508166.jpeg?auto=compress&cs=tinysrgb&w=900'},
  {id:'kit-churrasquinho',categoria:'Kits',nome:'Kit Churrasquinho',preco:75,unidade:'kit',ativo:true,descricao:'500g Fraldinha + 500g Alcatra + 500g Contrafilé + 500g Costela Suína',imagem:'https://images.pexels.com/photos/15508166/pexels-photo-15508166.jpeg?auto=compress&cs=tinysrgb&w=900'}
];
