window.SEED_PRODUCTS = [
  {id:'suino-bisteca',categoria:'Suíno',nome:'Bisteca',preco:19,unidade:'kg',ativo:true},
  {id:'suino-bife',categoria:'Suíno',nome:'Bife',preco:21,unidade:'kg',ativo:true},
  {id:'suino-pernil',categoria:'Suíno',nome:'Pernil',preco:17,unidade:'kg',ativo:true},
  {id:'suino-palheta',categoria:'Suíno',nome:'Palheta',preco:17,unidade:'kg',ativo:true},
  {id:'suino-barriga',categoria:'Suíno',nome:'Barriga',preco:20,unidade:'kg',ativo:true},
  {id:'suino-costela',categoria:'Suíno',nome:'Costela',preco:23,unidade:'kg',ativo:true},
  {id:'sarrabulho',categoria:'Suíno',nome:'Sarrabulho',preco:7,unidade:'kg',ativo:true},
  {id:'kit-feijoada',categoria:'Suíno',nome:'Kit Feijoada',preco:10,unidade:'kg',ativo:true},
  {id:'toucinho',categoria:'Suíno',nome:'Toucinho',preco:12,unidade:'kg',ativo:true},
  {id:'tripa',categoria:'Suíno',nome:'Tripa',preco:25,unidade:'kg',ativo:true},

  {id:'bovino-bisteca',categoria:'Bovino',nome:'Bisteca',preco:32,unidade:'kg',ativo:true},
  {id:'bovino-bife',categoria:'Bovino',nome:'Bife',preco:39,unidade:'kg',ativo:true},
  {id:'carne-moida',categoria:'Bovino',nome:'Carne Moída',preco:34,unidade:'kg',ativo:true},
  {id:'carne-moida-especial',categoria:'Bovino',nome:'Carne Moída Especial',preco:20,unidade:'kg',ativo:true},
  {id:'picadinho',categoria:'Bovino',nome:'Picadinho',preco:34,unidade:'kg',ativo:true},
  {id:'lombo',categoria:'Bovino',nome:'Lombo',preco:28,unidade:'kg',ativo:true},
  {id:'strogonoff',categoria:'Bovino',nome:'Strogonoff',preco:39,unidade:'kg',ativo:true},
  {id:'costela-peito',categoria:'Bovino',nome:'Costela / Peito',preco:27,unidade:'kg',ativo:true},
  {id:'figado',categoria:'Bovino',nome:'Fígado',preco:18,unidade:'kg',ativo:true},
  {id:'coxao-mole',categoria:'Bovino',nome:'Coxão Mole',preco:45,unidade:'kg',ativo:true},
  {id:'coxao-duro',categoria:'Bovino',nome:'Coxão Duro',preco:40,unidade:'kg',ativo:true},
  {id:'lagarto',categoria:'Bovino',nome:'Lagarto',preco:40,unidade:'kg',ativo:true},
  {id:'patinho',categoria:'Bovino',nome:'Patinho',preco:45,unidade:'kg',ativo:true},
  {id:'osso-buco',categoria:'Bovino',nome:'Osso Buco',preco:28,unidade:'kg',ativo:true},
  {id:'panelada',categoria:'Bovino',nome:'Panelada',preco:18,unidade:'kg',ativo:true},
  {id:'coracao',categoria:'Bovino',nome:'Coração (peça inteira)',preco:19,unidade:'kg',ativo:true},
  {id:'rabada',categoria:'Bovino',nome:'Rabada (peça inteira)',preco:28,unidade:'kg',ativo:true},
  {id:'mao-de-vaca',categoria:'Bovino',nome:'Mão de Vaca (peça inteira)',preco:19,unidade:'kg',ativo:true},

  {id:'kit-familia',categoria:'Kits',nome:'Kit Família',preco:130,unidade:'kit',ativo:true,descricao:'1kg Picadinho + 1kg Carne Moída + 1kg Cozido Bovino + 1kg Pernil Suíno + 1kg Bisteca Suína'},
  {id:'kit-premium',categoria:'Kits',nome:'Kit Premium',preco:90,unidade:'kit',ativo:true,descricao:'500g Strogonoff + 500g Bife do Patinho + 500g Bisteca Bovina + 500g Carne do Sol + 500g Bife Suíno'},
  {id:'kit-protein-70',categoria:'Kits',nome:'Kit Protein 70',preco:70,unidade:'kit',ativo:true,descricao:'500g Carne Moída + 500g Picadinho + 500g Bisteca Suína + 500g Pernil + 500g Bife'},
  {id:'kit-protein-50',categoria:'Kits',nome:'Kit Protein 50',preco:50,unidade:'kit',ativo:true,descricao:'500g Carne Moída + 500g Picadinho + 500g Bisteca Suína + 500g Pernil'},
  {id:'kit-pettica',categoria:'Kits',nome:'Kit Pettica',preco:90,unidade:'kit',ativo:true,descricao:'500g Carne do Sol + 500g Fraldinha + 500g Contrafilé + 500g Picanha Suína + 500g Linguiça Premium'},
  {id:'kit-churrasquinho',categoria:'Kits',nome:'Kit Churrasquinho',preco:75,unidade:'kit',ativo:true,descricao:'500g Fraldinha + 500g Alcatra + 500g Contrafilé + 500g Costela Suína'}
];
