/* Vitrine e categoria Promoções - O Peitica */
(function(){
  const cfg=window.APP_CONFIG||{};
  const moneyPromo=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
  function bool(v,def=true){if(v===null||v===undefined||v==='')return def;if(typeof v==='boolean')return v;return !['false','0','não','nao','inativo','off','indisponível','indisponivel'].includes(String(v).trim().toLowerCase())}
  function key(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim()}
  function fortalezaDay(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Fortaleza',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
  function normalizeDay(v){if(!v)return'';const s=String(v).trim();const m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);if(m)return`${m[1]}-${m[2]}-${m[3]}`;const br=s.match(/^(\d{2})\/(\d{2})\/(\d{4})/);if(br)return`${br[3]}-${br[2]}-${br[1]}`;const d=new Date(s);if(Number.isNaN(d.getTime()))return'';return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Fortaleza',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
  function inPromoPeriod(p){const today=fortalezaDay(),start=normalizeDay(p.promo_inicio||p.promocao_inicio||''),end=normalizeDay(p.promo_fim||p.promocao_fim||'');if(start&&today<start)return false;if(end&&today>end)return false;return true}
  function normalPrice(p){return Number(p.preco_original??p.preco??0)||0}
  function isPromo(p){const normal=normalPrice(p),promo=Number(p.preco_promocional||0);return bool(p.ativo,true)&&bool(p.promocao,false)&&promo>0&&normal>0&&promo<normal&&inPromoPeriod(p)}
  function selectedCategory(){const active=document.querySelector('#categoryTabs button.active');return active?active.textContent.replace(/🔥/g,'').trim():'Todos'}
  function promosForCategory(list){const cat=selectedCategory();return list.filter(p=>isPromo(p)&&(cat==='Todos'||cat==='Promoções'||key(p.categoria)===key(cat)))}
  function ensurePromoTab(list){
    const tabs=document.getElementById('categoryTabs');if(!tabs)return;
    const promos=list.filter(isPromo);let btn=tabs.querySelector('[data-promo-tab="1"]');
    if(!promos.length){btn?.remove();return}
    if(!btn){btn=document.createElement('button');btn.type='button';btn.dataset.promoTab='1';btn.dataset.baseLabel='Promoções';btn.className='promo-category-tab';btn.innerHTML='<span class="promo-tab-icon">🔥</span> Promoções';tabs.appendChild(btn);
      btn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();tabs.querySelectorAll('button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');filterProductCards(list,'Promoções');render(list)});
    }
    btn.innerHTML=`<span class="promo-tab-icon">🔥</span> Promoções <b>${promos.length}</b>`;
  }
  function filterProductCards(list,cat){const map=new Map(list.map(p=>[key(p.nome),p]));document.querySelectorAll('.product-card').forEach(card=>{const p=map.get(key(card.querySelector('h3')?.textContent));if(!p)return;const show=cat==='Promoções'?isPromo(p):bool(p.ativo,true);card.style.display=show?'':'none'});if(cat==='Promoções')bringPromoCardsFirst(list.filter(isPromo))}
  function updateCategoryBadges(list){const promos=list.filter(isPromo);const cats=new Set(promos.map(p=>key(p.categoria)));document.querySelectorAll('#categoryTabs button:not([data-promo-tab])').forEach(btn=>{const base=btn.dataset.baseLabel||btn.textContent.replace(/🔥/g,'').trim();btn.dataset.baseLabel=base;const has=base==='Todos'?promos.length>0:cats.has(key(base));btn.classList.toggle('has-promo',has);btn.textContent=has?`${base} 🔥`:base;btn.title=has?'Há promoção ativa nesta categoria':''})}
  function ensureSection(){let s=document.getElementById('promoSection');if(s)return s;s=document.createElement('section');s.id='promoSection';s.className='promo-showcase';s.hidden=true;s.innerHTML='<div class="promo-showcase-head"><div><span id="promoEyebrow">🔥 PROMOÇÕES DO DIA</span><h2 id="promoTitle">Ofertas em destaque</h2><p>Aproveite antes de escolher os demais produtos.</p></div><b id="promoCount"></b></div><div id="promoGrid" class="promo-grid"></div>';const tabs=document.getElementById('categoryTabs');if(tabs)tabs.insertAdjacentElement('afterend',s);else document.querySelector('.catalog-toolbar')?.insertAdjacentElement('afterend',s);return s}
  function patchCards(list){const map=new Map(list.map(p=>[key(p.nome),p]));document.querySelectorAll('.product-card').forEach(card=>{const h=card.querySelector('h3');if(!h)return;const p=map.get(key(h.textContent));if(!p)return;card.classList.remove('is-promo');card.querySelectorAll('.promo-live-badge,.old-price').forEach(x=>x.remove());const price=card.querySelector('.price'),row=card.querySelector('.price-row'),normal=normalPrice(p);if(isPromo(p)){card.classList.add('is-promo');const media=card.querySelector('.product-media');if(media){const badge=document.createElement('span');badge.className='promo-live-badge';badge.textContent='🔥 OFERTA DO DIA';media.appendChild(badge)}if(row&&price){const old=document.createElement('del');old.className='old-price';old.textContent=moneyPromo(normal);row.insertBefore(old,price);price.textContent=moneyPromo(p.preco_promocional)}const live=card.querySelector('.live-calc');if(live)live.innerHTML=`1 kg = <strong>${moneyPromo(p.preco_promocional)}</strong>`}else if(price)price.textContent=moneyPromo(normal)})}
  function bringPromoCardsFirst(promos){if(!promos.length)return;const grid=document.getElementById('productGrid');if(!grid)return;const names=new Set(promos.map(p=>key(p.nome)));[...grid.querySelectorAll('.product-card')].filter(c=>names.has(key(c.querySelector('h3')?.textContent))).reverse().forEach(c=>grid.prepend(c))}
  function render(list){ensurePromoTab(list);updateCategoryBadges(list);const section=ensureSection(),grid=document.getElementById('promoGrid'),count=document.getElementById('promoCount'),promos=promosForCategory(list),cat=selectedCategory();section.hidden=!promos.length;const eyebrow=document.getElementById('promoEyebrow'),title=document.getElementById('promoTitle');if(eyebrow)eyebrow.textContent=cat==='Promoções'?'🔥 TODAS AS PROMOÇÕES':cat==='Todos'?'🔥 PROMOÇÕES DO DIA':`🔥 PROMOÇÕES DE ${cat.toUpperCase()}`;if(title)title.textContent=cat==='Promoções'?'Produtos em promoção':cat==='Todos'?'Ofertas em destaque':`Ofertas de ${cat}`;if(count)count.textContent=promos.length?`${promos.length} ${promos.length===1?'oferta':'ofertas'}`:'';if(grid)grid.innerHTML=promos.map(p=>`<article class="promo-card"><div class="promo-card-media">${p.imagem?`<img src="${String(p.imagem).replace(/"/g,'&quot;')}" alt="${String(p.nome||'Produto').replace(/"/g,'&quot;')}">`:''}<span>🔥 OFERTA DO DIA</span></div><div class="promo-card-body"><small>${p.categoria||''}</small><h3>${p.nome||'Produto'}</h3>${p.descricao?`<p>${p.descricao}</p>`:''}<div class="promo-prices"><del>${moneyPromo(normalPrice(p))}</del><strong>${moneyPromo(p.preco_promocional)}</strong><em>${String(p.unidade||'kg').toLowerCase()==='kit'?'/ kit':'/ kg'}</em></div></div></article>`).join('');patchCards(list);if(cat==='Promoções')filterProductCards(list,'Promoções');else setTimeout(()=>bringPromoCardsFirst(promos),0)}
  async function load(){const endpoint=String(cfg.ORDER_WEBAPP_URL||'').trim();if(!endpoint)return;try{const u=new URL(endpoint);u.searchParams.set('action','products');u.searchParams.set('_t',Date.now());const r=await fetch(u.toString(),{cache:'no-store',headers:{'Cache-Control':'no-cache'}});const j=await r.json();if(j.ok&&Array.isArray(j.products))render(j.products)}catch(e){console.warn('[Promoções O Peitica]',e)}}
  function start(){ensureSection();load();document.getElementById('categoryTabs')?.addEventListener('click',e=>{if(e.target.closest('[data-promo-tab]'))return;setTimeout(load,80)});setInterval(()=>{if(!document.hidden)load()},3000);window.addEventListener('focus',load);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load()});window.OPEITICA_PROMO_SYNC=load}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();