/* Vitrine de promoções do dia - O Peitica */
(function(){
  const cfg=window.APP_CONFIG||{};
  const moneyPromo=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
  function bool(v,def=true){if(v===null||v===undefined||v==='')return def;if(typeof v==='boolean')return v;return !['false','0','não','nao','inativo','off','indisponível','indisponivel'].includes(String(v).trim().toLowerCase())}
  function dateOk(p){const now=new Date(),a=p.promo_inicio?new Date(p.promo_inicio):null,b=p.promo_fim?new Date(p.promo_fim):null;return(!a||isNaN(a)||now>=a)&&(!b||isNaN(b)||now<=b)}
  function ensureSection(){let s=document.getElementById('promoSection');if(s)return s;s=document.createElement('section');s.id='promoSection';s.className='promo-showcase';s.hidden=true;s.innerHTML='<div class="promo-showcase-head"><div><span>🔥 PROMOÇÕES DO DIA</span><h2>Ofertas especiais</h2><p>Preços promocionais enquanto durarem os estoques.</p></div><b id="promoCount"></b></div><div id="promoGrid" class="promo-grid"></div>';
    const toolbar=document.querySelector('.catalog-toolbar');if(toolbar)toolbar.insertAdjacentElement('afterend',s);else document.querySelector('main')?.prepend(s);return s}
  function render(list){const section=ensureSection(),grid=document.getElementById('promoGrid'),count=document.getElementById('promoCount');const promos=list.filter(p=>bool(p.ativo,true)&&bool(p.promocao,false)&&Number(p.preco_promocional||0)>0&&dateOk(p));section.hidden=!promos.length;if(count)count.textContent=promos.length?`${promos.length} ${promos.length===1?'oferta':'ofertas'}`:'';if(!grid)return;grid.innerHTML=promos.map(p=>`<article class="promo-card" data-promo-id="${String(p.id||'')}"><div class="promo-card-media">${p.imagem?`<img src="${String(p.imagem).replace(/"/g,'&quot;')}" alt="${String(p.nome||'Produto').replace(/"/g,'&quot;')}">`:''}<span>🔥 OFERTA DO DIA</span></div><div class="promo-card-body"><small>${p.categoria||''}</small><h3>${p.nome||'Produto'}</h3>${p.descricao?`<p>${p.descricao}</p>`:''}<div class="promo-prices"><del>${moneyPromo(p.preco)}</del><strong>${moneyPromo(p.preco_promocional)}</strong><em>${String(p.unidade||'kg').toLowerCase()==='kit'?'/ kit':'/ kg'}</em></div><button type="button" data-go-product="${String(p.id||'')}">VER PRODUTO</button></div></article>`).join('');grid.querySelectorAll('[data-go-product]').forEach(btn=>btn.onclick=()=>{const id=btn.dataset.goProduct;const prod=(window.state?.products||[]).find?.(x=>String(x.id)===String(id));if(prod&&typeof state!=='undefined'){state.category='Todos';state.query=prod.nome;if(document.getElementById('searchInput'))document.getElementById('searchInput').value=prod.nome;if(typeof buildTabs==='function')buildTabs();if(typeof renderProducts==='function')renderProducts();document.getElementById('productGrid')?.scrollIntoView({behavior:'smooth',block:'start'});}})}
  async function load(){const endpoint=String(cfg.ORDER_WEBAPP_URL||'').trim();if(!endpoint)return;try{const u=new URL(endpoint);u.searchParams.set('action','products');u.searchParams.set('_t',Date.now());const r=await fetch(u.toString(),{cache:'no-store'});const j=await r.json();if(j.ok&&Array.isArray(j.products))render(j.products)}catch(e){console.warn('[Promoções O Peitica]',e)}}
  function start(){ensureSection();load();setInterval(()=>{if(!document.hidden)load()},5000);window.addEventListener('focus',load);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load()});window.OPEITICA_PROMO_SYNC=load}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();