/* Vitrine de promoções do dia - O Peitica */
(function(){
  const cfg=window.APP_CONFIG||{};
  const moneyPromo=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
  function bool(v,def=true){if(v===null||v===undefined||v==='')return def;if(typeof v==='boolean')return v;return !['false','0','não','nao','inativo','off','indisponível','indisponivel'].includes(String(v).trim().toLowerCase())}
  function key(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim()}
  function isPromo(p){const normal=Number(p.preco||0),promo=Number(p.preco_promocional||0);return bool(p.ativo,true)&&bool(p.promocao,false)&&promo>0&&normal>0&&promo<normal}
  function selectedCategory(){const active=document.querySelector('#categoryTabs button.active');return active?active.textContent.trim():'Todos'}
  function promosForCategory(list){const cat=selectedCategory();return list.filter(p=>isPromo(p)&&(cat==='Todos'||key(p.categoria)===key(cat)))}
  function ensureSection(){let s=document.getElementById('promoSection');if(s)return s;s=document.createElement('section');s.id='promoSection';s.className='promo-showcase';s.hidden=true;s.innerHTML='<div class="promo-showcase-head"><div><span>🔥 PROMOÇÃO NESTA CATEGORIA</span><h2>Ofertas em destaque</h2><p>Aproveite antes de escolher os demais produtos.</p></div><b id="promoCount"></b></div><div id="promoGrid" class="promo-grid"></div>';const tabs=document.getElementById('categoryTabs');if(tabs)tabs.insertAdjacentElement('afterend',s);else document.querySelector('.catalog-toolbar')?.insertAdjacentElement('afterend',s);return s}
  function patchCards(list){const map=new Map(list.map(p=>[key(p.nome),p]));document.querySelectorAll('.product-card').forEach(card=>{const h=card.querySelector('h3');if(!h)return;const p=map.get(key(h.textContent));if(!p)return;card.style.display=bool(p.ativo,true)?'':'none';card.classList.remove('is-promo');card.querySelectorAll('.promo-live-badge,.old-price').forEach(x=>x.remove());const price=card.querySelector('.price'),row=card.querySelector('.price-row');if(isPromo(p)){card.classList.add('is-promo');const media=card.querySelector('.product-media');if(media){const badge=document.createElement('span');badge.className='promo-live-badge';badge.textContent='🔥 OFERTA DO DIA';media.appendChild(badge)}if(row&&price){const old=document.createElement('del');old.className='old-price';old.textContent=moneyPromo(p.preco);row.insertBefore(old,price);price.textContent=moneyPromo(p.preco_promocional)}const live=card.querySelector('.live-calc');if(live){live.innerHTML=`1 kg = <strong>${moneyPromo(p.preco_promocional)}</strong>`}}else if(price){price.textContent=moneyPromo(p.preco)}})}
  function bringPromoCardsFirst(promos){if(!promos.length)return;const grid=document.getElementById('productGrid');if(!grid)return;const names=new Set(promos.map(p=>key(p.nome)));[...grid.querySelectorAll('.product-card')].filter(c=>names.has(key(c.querySelector('h3')?.textContent))).reverse().forEach(c=>grid.prepend(c))}
  function render(list){const section=ensureSection(),grid=document.getElementById('promoGrid'),count=document.getElementById('promoCount'),promos=promosForCategory(list);section.hidden=!promos.length;if(count)count.textContent=promos.length?`${promos.length} ${promos.length===1?'oferta':'ofertas'}`:'';if(grid)grid.innerHTML=promos.map(p=>`<article class="promo-card" data-promo-id="${String(p.id||'')}"><div class="promo-card-media">${p.imagem?`<img src="${String(p.imagem).replace(/"/g,'&quot;')}" alt="${String(p.nome||'Produto').replace(/"/g,'&quot;')}">`:''}<span>🔥 OFERTA DO DIA</span></div><div class="promo-card-body"><small>${p.categoria||''}</small><h3>${p.nome||'Produto'}</h3>${p.descricao?`<p>${p.descricao}</p>`:''}<div class="promo-prices"><del>${moneyPromo(p.preco)}</del><strong>${moneyPromo(p.preco_promocional)}</strong><em>${String(p.unidade||'kg').toLowerCase()==='kit'?'/ kit':'/ kg'}</em></div><button type="button" data-go-product="${String(p.id||'')}">ESCOLHER ESTA OFERTA</button></div></article>`).join('');patchCards(list);setTimeout(()=>bringPromoCardsFirst(promos),0);grid?.querySelectorAll('[data-go-product]').forEach(btn=>btn.onclick=()=>{const p=promos.find(x=>String(x.id)===String(btn.dataset.goProduct));const target=[...document.querySelectorAll('.product-card')].find(c=>key(c.querySelector('h3')?.textContent)===key(p?.nome));if(target)target.scrollIntoView({behavior:'smooth',block:'center'})})}
  async function load(){const endpoint=String(cfg.ORDER_WEBAPP_URL||'').trim();if(!endpoint)return;try{const u=new URL(endpoint);u.searchParams.set('action','products');u.searchParams.set('_t',Date.now());const r=await fetch(u.toString(),{cache:'no-store',headers:{'Cache-Control':'no-cache'}});const j=await r.json();if(j.ok&&Array.isArray(j.products))render(j.products)}catch(e){console.warn('[Promoções O Peitica]',e)}}
  function start(){ensureSection();load();document.getElementById('categoryTabs')?.addEventListener('click',()=>setTimeout(load,60));setInterval(()=>{if(!document.hidden)load()},3000);window.addEventListener('focus',load);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load()});window.OPEITICA_PROMO_SYNC=load}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();